# Generated by Django 5.1.3 on 2024-12-29 12:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS billing;"),
        migrations.CreateModel(
            name="ActionCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=255)),
                ("classification", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": '"billing"."action_code"',
                "unique_together": {("code", "classification")},
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Actor",
                "db_table": '"billing"."actor"',
                "unique_together": {("name", "number")},
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("bill_actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.actor")),
            ],
            options={
                "verbose_name": "Billing",
                "db_table": '"billing"."billing"',
                "unique_together": {("title", "number")},
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Client",
                "db_table": '"billing"."client"',
                "unique_together": {("name", "number")},
            },
        ),
        migrations.CreateModel(
            name="ClientPayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.client")),
            ],
            options={
                "verbose_name": "Client <-> Payer mapping",
                "db_table": '"billing"."client_payer"',
            },
        ),
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.client")),
                ("matter_actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.actor")),
            ],
            options={
                "verbose_name": "Matter",
                "db_table": '"billing"."matter"',
                "unique_together": {("title", "number")},
            },
        ),
        migrations.CreateModel(
            name="Payer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                (
                    "clients",
                    models.ManyToManyField(related_name="payers", through="billing.ClientPayer", to="billing.client"),
                ),
            ],
            options={
                "verbose_name": "Payer",
                "db_table": '"billing"."payer"',
                "unique_together": {("name", "number")},
            },
        ),
        migrations.AddField(
            model_name="clientpayer",
            name="payer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.payer"),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8314a138-32be-4194-8b4f-f84be29f76dc"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("time", models.IntegerField(db_comment="Time spent on the activity, seconds")),
                ("rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("code", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.actioncode")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.actor")),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.bill")),
                ("matter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.matter")),
            ],
            options={
                "verbose_name": "Action",
                "db_table": '"billing"."action"',
                "unique_together": {("title", "number")},
            },
        ),
    ]
