# Generated by Django 5.1.3 on 2024-12-29 12:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS guideline;"),
        migrations.CreateModel(
            name="Guideline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("firmwide", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Guideline",
                "verbose_name_plural": "Guidelines",
                "db_table": '"guideline"."guideline"',
            },
        ),
        migrations.CreateModel(
            name="GuidelineActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.actor")),
                (
                    "guideline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.guideline"),
                ),
            ],
            options={
                "verbose_name": "Guideline <-> Actor",
                "verbose_name_plural": "Guideline <-> Client Mapping",
                "db_table": '"guideline"."guideline_actor"',
                "unique_together": {("guideline", "actor")},
            },
        ),
        migrations.AddField(
            model_name="guideline",
            name="actors",
            field=models.ManyToManyField(through="guidelines.GuidelineActor", to="billing.actor"),
        ),
        migrations.CreateModel(
            name="GuidelineClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.client")),
                (
                    "guideline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.guideline"),
                ),
            ],
            options={
                "verbose_name": "Guideline <-> Client",
                "verbose_name_plural": "Guideline <-> Client Mapping",
                "db_table": '"guideline"."guideline_client"',
                "unique_together": {("guideline", "client")},
            },
        ),
        migrations.AddField(
            model_name="guideline",
            name="client",
            field=models.ManyToManyField(through="guidelines.GuidelineClient", to="billing.client"),
        ),
        migrations.CreateModel(
            name="GuidelineMatter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "guideline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.guideline"),
                ),
                ("matter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.matter")),
            ],
            options={
                "verbose_name": "Guideline <-> Matter",
                "verbose_name_plural": "Guideline <-> Matter Mapping",
                "db_table": '"guideline"."guideline_matter"',
                "unique_together": {("guideline", "matter")},
            },
        ),
        migrations.AddField(
            model_name="guideline",
            name="matter",
            field=models.ManyToManyField(through="guidelines.GuidelineMatter", to="billing.matter"),
        ),
        migrations.CreateModel(
            name="GuidelinePayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "guideline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.guideline"),
                ),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.payer")),
            ],
            options={
                "verbose_name": "Guideline <-> Payer",
                "verbose_name_plural": "Guideline <-> Payer mapping",
                "db_table": '"guideline"."guideline_payer"',
                "unique_together": {("guideline", "payer")},
            },
        ),
        migrations.AddField(
            model_name="guideline",
            name="payers",
            field=models.ManyToManyField(through="guidelines.GuidelinePayer", to="billing.payer"),
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("firmwide", models.BooleanField(default=False)),
                (
                    "guideline",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="guidelines.guideline"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "db_table": '"guideline"."rule"',
            },
        ),
        migrations.CreateModel(
            name="RuleActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.actor")),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.rule")),
            ],
            options={
                "verbose_name": "Rule <-> Actor",
                "verbose_name_plural": "Rule <-> Client Mapping",
                "db_table": '"guideline"."rule_actor"',
                "unique_together": {("rule", "actor")},
            },
        ),
        migrations.CreateModel(
            name="RuleClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.client")),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.rule")),
            ],
            options={
                "verbose_name": "Rule <-> Client",
                "verbose_name_plural": "Rule <-> Client Mapping",
                "db_table": '"guideline"."rule_client"',
                "unique_together": {("rule", "client")},
            },
        ),
        migrations.CreateModel(
            name="RuleMatter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("matter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.matter")),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.rule")),
            ],
            options={
                "verbose_name": "Rule <-> Matter",
                "verbose_name_plural": "Rule <-> Matter Mapping",
                "db_table": '"guideline"."rule_matter"',
                "unique_together": {("rule", "matter")},
            },
        ),
        migrations.CreateModel(
            name="RulePayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("4f4d5b13-eded-400e-a024-0fb6b88e167c"), primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.payer")),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guidelines.rule")),
            ],
            options={
                "verbose_name": "Rule <-> Payer",
                "verbose_name_plural": "Rule <-> Payer mapping",
                "db_table": '"guideline"."rule_payer"',
                "unique_together": {("rule", "payer")},
            },
        ),
    ]
