# Generated by Django 5.1.3 on 2024-12-29 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS delegation;"),
        migrations.CreateModel(
            name="UserActor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.actor")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Delegation",
                "db_table": '"delegation"."user_actor"',
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period_end__gt", models.F("period_start"))), name="period_end_start_check"
                    )
                ],
            },
        ),
    ]
